version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bvida
      - MERCADOPAGO_TOKEN=APP_USR-7619237250289702-080618-5e089334b7e4e9f6993ffae5d446f5cb-68389981
      - MERCADOPAGO_PUBLIC_KEY=APP_USR-11f3ba80-7c4c-4627-b2f2-dbb8f7645089
      - FRONTEND_URL=http://localhost:4000
      - MERCADOPAGO_SUCCESS_URL=http://localhost:4000/pago-exitoso
      - MERCADOPAGO_FAILURE_URL=http://localhost:4000/pago-fallido
      - NGROK_URL=https://webhook.site/tu-url-unica
      - EMAIL_USER=makagonzalez17@gmail.com
      - EMAIL_PASS=kiii lajt ydbv shex
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: 