version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "4001:4000"
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bvida
      - MERCADOPAGO_TOKEN=tu_token_aqui
      - FRONTEND_URL=http://localhost:4000
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: 